Repository jjik-muk/sikdorak, pull requests merged in 2022-07, with the labels that each got.

#3 [common] 리드미 문서 초안 작성
  README.md
Labels: 📝 docs, 👫 common

#12 [BE] 프로젝트 초기 세팅
  be/.gitignore
  be/README.md
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/com/jjikmuk/sikdorak/SikdorakApplication.java
  be/src/test/java/com/jjikmuk/sikdorak/SikdorakApplicationTests.java
Labels: 🤖 BE, 🏗️ build

#14 [FE] 프로젝트 초기 세팅
  fe/.eslintrc
  fe/.gitignore
  fe/.prettierrc
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/public/robots.txt
  fe/src/App.tsx
  fe/src/index.tsx
  fe/tsconfig.json
Labels: 🌐 FE, ✨ feature

#16 [FE] 로그인 페이지 레이아웃 생성
  fe/package.json
  fe/src/App.test.tsx
  fe/src/App.tsx
  fe/src/components/Login/LoginButton/LoginButton.styled.ts
  fe/src/components/Login/LoginButton/LoginButton.test.tsx
  fe/src/components/Login/LoginButton/LoginButton.tsx
  fe/src/components/Login/LoginInput/LoginInput.styled.ts
  fe/src/components/Login/LoginInput/LoginInput.test.tsx
  fe/src/components/Login/LoginInput/LoginInput.tsx
  fe/src/components/Logo/Logo.test.tsx
  fe/src/components/Logo/Logo.tsx
  fe/src/constants/text.ts
  fe/src/pages/Login/Login.styled.ts
  fe/src/pages/Login/Login.test.tsx
  fe/src/pages/Login/Login.tsx
  fe/src/setupTests.ts
  fe/src/styles/GlobalStyle.ts
  fe/src/utils/utils.ts
Labels: 🌐 FE, ✨ feature

#17 [BE] 리뷰 작성(생성) API 기능 구현과 테스트
  be/build.gradle
  be/src/main/java/com/jjikmuk/sikdorak/SikdorakApplication.java
  be/src/main/java/com/jjikmuk/sikdorak/common/BaseResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/common/CodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/domain/BaseTimeEntity.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/ExceptionCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/GlobalExceptionHandler.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/NotFoundErrorCodeException.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/SikdorakRuntimeException.java
  be/src/main/java/com/jjikmuk/sikdorak/common/response/CommonResponseEntity.java
  be/src/main/java/com/jjikmuk/sikdorak/review/controller/ReviewController.java
  be/src/main/java/com/jjikmuk/sikdorak/review/controller/request/ReviewInsertRequest.java
  be/src/main/java/com/jjikmuk/sikdorak/review/controller/response/ReviewInsertResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Review.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/ReviewContent.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/ReviewScore.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/ReviewVisibility.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/ReviewVisitedDate.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Tag.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Tags.java
  be/src/main/java/com/jjikmuk/sikdorak/review/exception/InvalidReviewContentException.java
  be/src/main/java/com/jjikmuk/sikdorak/review/exception/InvalidReviewScoreException.java
  be/src/main/java/com/jjikmuk/sikdorak/review/exception/InvalidReviewVisibilityException.java
  be/src/main/java/com/jjikmuk/sikdorak/review/exception/InvalidReviewVisitedDateException.java
  be/src/main/java/com/jjikmuk/sikdorak/review/exception/InvalidTagException.java
  be/src/main/java/com/jjikmuk/sikdorak/review/exception/InvalidTagsException.java
  be/src/main/java/com/jjikmuk/sikdorak/review/repository/ReviewRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/review/service/ReviewService.java
  be/src/main/java/com/jjikmuk/sikdorak/store/domain/Store.java
  be/src/main/java/com/jjikmuk/sikdorak/store/exception/StoreNotFoundException.java
  be/src/main/java/com/jjikmuk/sikdorak/store/repository/StoreRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/store/service/StoreService.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/InitAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/ReviewAccecptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/review/domain/ReviewContentTest.java
  be/src/test/java/com/jjikmuk/sikdorak/review/domain/ReviewScoreTest.java
  be/src/test/java/com/jjikmuk/sikdorak/review/domain/ReviewVisibilityTest.java
  be/src/test/java/com/jjikmuk/sikdorak/review/domain/ReviewVisitedDateTest.java
  be/src/test/java/com/jjikmuk/sikdorak/review/domain/TagTest.java
  be/src/test/java/com/jjikmuk/sikdorak/review/domain/TagsTest.java
  be/src/test/resources/application.yml
Labels: 🤖 BE, ✨ feature

#23 [common] BE-dev 브랜치 push/PR 시 자동 테스트를 한다.
  .github/workflows/CI-BE.yml
Labels: 🤖 BE, 🧪 test, 🏭 DevOps

#27 [BE] API 문서 관련 설정 및 리뷰 작성 API 문서 추가
  be/.gitignore
  be/build.gradle
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/InitAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/ReviewAcceptanceTest.java
Labels: 🤖 BE, 🏗️ build, 📝 docs

#34 [common] BE v0.0.1 인프라 프로비저닝
  infra/.gitignore
  infra/be/.terraform.lock.hcl
  infra/be/README.md
  infra/be/infra.tf
  infra/be/provider.tf
  infra/be/variables.tf
Labels: 👫 common, 🏭 Infra
