Repository jjik-muk/sikdorak, pull requests merged in 2022-09, with the labels that each got.

#131 [SDR-101] FE : User Detail, Review Write API 연동
  fe/src/App.tsx
  fe/src/components/CommonHeader/CommonHeader.styled.ts
  fe/src/components/CommonHeader/CommonHeader.tsx
  fe/src/components/ReviewDetail/UserProfile/UserProfile.styled.ts
  fe/src/components/ReviewList/Feed/Feed.tsx
  fe/src/components/ReviewWrite/Calendar/Calendar.styled.ts
  fe/src/components/ReviewWrite/Calendar/Calendar.tsx
  fe/src/components/ReviewWrite/ImgUpload/ImgUpload.styled.ts
  fe/src/components/ReviewWrite/ImgUpload/ImgUpload.tsx
  fe/src/components/ReviewWrite/PostScope/PostScope.styled.ts
  fe/src/components/ReviewWrite/PostScope/PostScope.tsx
  fe/src/components/ReviewWrite/RegistrationBtn/RegistrationBtn.tsx
  fe/src/components/ReviewWrite/RestaurantSearch/RestaurantSearch.tsx
  fe/src/components/ReviewWrite/SelectDay/SelectDay.tsx
  fe/src/components/ReviewWrite/Tag/TagContainer/TagContainer.styled.ts
  fe/src/components/ReviewWrite/Tag/TagContainer/TagContainer.tsx
  fe/src/components/ReviewWrite/Tag/TagInput/TagInput.tsx
  fe/src/components/ReviewWrite/Tag/TagItem/TagItem.styled.ts
  fe/src/components/ReviewWrite/Tag/TagItem/TagItem.tsx
  fe/src/components/ReviewWrite/Textarea/Textarea.tsx
  fe/src/components/ReviewWrite/WriteRating/StarRating/StarRating.tsx
  fe/src/constants/size.ts
  fe/src/context/MyUserInfoProvider.tsx
  fe/src/context/reviewDetailProvider.tsx
  fe/src/index.tsx
  fe/src/pages/Callback/Callback.tsx
  fe/src/pages/Login/Login.tsx
  fe/src/pages/ReviewDetail/ReviewDetail.tsx
  fe/src/pages/ReviewList/ReviewList.tsx
  fe/src/pages/ReviewWrite/ReviewWrite.styled.ts
  fe/src/pages/ReviewWrite/ReviewWrite.tsx
  fe/src/pages/StoreDetail/StoreDetail.tsx
  fe/src/pages/UserDetail/userDetail.styled.ts
  fe/src/pages/UserDetail/userDetail.tsx
  fe/src/utils/utils.ts
Labels: 🌐 FE, ✨ feature

#129 [SDR-226] common: 테라폼을 활용한 이미지 스토리지 목적의 s3, 스프링이 사용할 iam 유저 프로비저닝
  infra/s3_images/.terraform.lock.hcl
  infra/s3_images/iam.tf
  infra/s3_images/provider.tf
  infra/s3_images/s3.tf
  infra/s3_images/variabels.tf
Labels: 🏭 Infra

#132 [SDR-209] BE : 리뷰 추천 목록 조회 API의 데이터 조회 정렬 조건 수정
  be/src/main/java/com/jjikmuk/sikdorak/review/repository/ReviewRepository.java
  be/src/test/java/com/jjikmuk/sikdorak/common/DatabaseConfigurator.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewsRecommendIntegrationTest.java
Labels: 🤖 BE, 🐛 bug

#133 [SDR-233] BE : 리뷰 좋아요 API
  be/src/docs/asciidoc/review/review.adoc
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/ExceptionCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/review/controller/ReviewController.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Likes.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Review.java
  be/src/main/java/com/jjikmuk/sikdorak/review/exception/DuplicateLikeUserException.java
  be/src/main/java/com/jjikmuk/sikdorak/review/exception/NotFoundLikeUserException.java
  be/src/main/java/com/jjikmuk/sikdorak/review/repository/ReviewRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/review/service/ReviewService.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/review/ReviewLikeAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/review/ReviewSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/common/DatabaseConfigurator.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewLikeIntegrationTest.java
Labels: 🤖 BE, ✨ feature

#134 [SDR-252] BE : 위치기반 가게 목록 조회 Mock API
  be/src/docs/asciidoc/store/store.adoc
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/StoreController.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/request/UserLocationInfo.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/response/StoreRadiusSearchResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/store/service/StoreService.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/store/StoreSearchByRadiusAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/store/StoreSnippet.java
Labels: 🤖 BE, ✨ feature

#136 [SDR-255] BE : 리뷰 데이터 조회 시 좋아요 정보도 함께 반환하도록 개선
  be/src/main/java/com/jjikmuk/sikdorak/review/controller/response/reviewdetail/ReviewDetailLikeResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/review/controller/response/reviewdetail/ReviewDetailResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Likes.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Review.java
  be/src/main/java/com/jjikmuk/sikdorak/review/service/ReviewService.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/review/ReviewSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewSearchIntegrationTest.java
Labels: 🤖 BE, ♻️ refactor

#138 [SDR-207] common : BE팀 VPC, igw, subnet, route table 프로비저닝
  infra/vpc/.terraform.lock.hcl
  infra/vpc/provider.tf
  infra/vpc/vpc.tf
Labels: 👫 common, 🏭 Infra

#139 [SDR-54] common : BE-springboot에서 사용할 ECR 프로비저닝
  infra/ecr/.terraform.lock.hcl
  infra/ecr/ecr.tf
  infra/ecr/output.tf
  infra/ecr/provider.tf
Labels: 👫 common, 🏭 Infra

#141 [SDR-261] common : BE팀의 ECR Lifecycle Policy 프로비저닝
  infra/ecr/ecr.tf
  infra/ecr/json-policies/lifecyclepolicy.json
Labels: 👫 common, 🏭 Infra

#142 [SDR-262] BE : cookie의 만료시간을 refreshToken의 만료시간과 동일하게 설정하도록 수정
  .github/PULL_REQUEST_TEMPLATE.md
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/controller/OAuthController.java
Labels: 🤖 BE, 🐛 bug

#143 [SDR-260] common : 테스트/운영 서버 배포를 위한 jib 분리
  .github/workflows/CD-BE.yml
  be/build.gradle
  be/config-docker/profile_dev.gradle
  be/config-docker/profile_prod.gradle
Labels: 🏗️ build, 👫 common, 🏭 Infra

#148 [SDR-269] BE : 유저 검색 API
  be/src/docs/asciidoc/user/user.adoc
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/review/service/ReviewService.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/controller/UserController.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/UserRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/service/UserService.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/user/user/UserSearchAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/user/user/UserSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserSearchIntegrationTest.java
Labels: 🤖 BE, ✨ feature

#152 [SDR-101] fix: context 파일명 대문자로 변경
  fe/src/context/ReviewDetailProvider.tsx
  fe/src/context/ReviewWriteProvider.tsx
  fe/src/pages/UserDetail/UserDetail.styled.ts
  fe/src/pages/UserDetail/UserDetail.tsx
Labels: 🌐 FE

#153 [SDR-271] FE : 백엔드 API 서버 URL .env로 이동
  fe/src/App.tsx
  fe/src/components/Common/Header/CommonHeader.tsx
  fe/src/components/ReviewDetail/Menu/Menu.tsx
  fe/src/components/ReviewDetail/WriteComment/WriteComment.tsx
  fe/src/components/ReviewWrite/RegistrationBtn/RegistrationBtn.tsx
  fe/src/components/UserDetail/FollowButton/FollowButton.tsx
  fe/src/constants/dummyData.ts
  fe/src/hooks/useLike.ts
  fe/src/hooks/useUploadImage.ts
  fe/src/pages/Callback/Callback.tsx
  fe/src/pages/Login/Login.tsx
  fe/src/pages/ReviewDetail/ReviewDetail.tsx
  fe/src/pages/ReviewList/ReviewList.tsx
  fe/src/pages/ReviewWrite/ReviewWrite.tsx
  fe/src/pages/UserDetail/UserDetail.tsx
  fe/src/pages/UserDetail/userDetail.tsx
  fe/src/utils/utils.ts
Labels: 🌐 FE, ✨ feature

#150 [SDR-55] common : 운영 서버 DB, RDS(MySQL) 프로비저닝
  infra/rds/.terraform.lock.hcl
  infra/rds/outputs.tf
  infra/rds/provider.tf
  infra/rds/rds.tf
  infra/rds/security_group.tf
  infra/rds/variables.tf
  infra/vpc/outputs.tf
  infra/vpc/security_group.tf
  infra/vpc/vpc.tf
  infra/vpc/vpc2.tf
Labels: 👫 common, 🏭 Infra

#157 [SDR-281] common : CI infra(terraform) 정적 분석 sonarcloud 추가
  .github/workflows/CI-Infra.yml
Labels: 🧪 test, 👫 common, 🏭 Infra

#159 [SDR-281] common : 테라폼 파일 이름 변경 provider.tf -> main.tf / infra 프로젝트에 Sonarsource 적용 확인
  .github/workflows/CI-Infra.yml
  infra/FE_s3_cloudfront/main.tf
  infra/be/heroku/main.tf
  infra/be/sonarcloud/main.tf
  infra/ecr/main.tf
  infra/ecs/main.tf
  infra/iam/main.tf
  infra/rds/main.tf
  infra/s3_images/main.tf
  infra/sonar-project.properties
  infra/vpc/main.tf
Labels: 👫 common, 🏭 Infra

#160 [SDR-283] common : 불필요한 sonar-project.properties 제거
  .github/workflows/CI-FE.yml
  .github/workflows/CI-Infra.yml
  .sonarcloud.properties
  infra/sonar-project.properties
  sonar-project.properties
Labels: 📝 docs, 🏭 Infra

#161 [SDR-285] common : readme 프로젝트 소개 추가
  README.md
  be/README.md
  infra/README.md
Labels: 📝 docs, 👫 common

#162 [SDR-289] common : FE 팀 CD에 .env 파일 생성
  .github/workflows/CD-FE.yml
Labels: 🏗️ build, 👫 common, 🏭 Infra

#163 [SDR-290] common : CD - BE 팀 ECS에 자동 배포
  .github/workflows/CD-BE-ECS.yml
  .github/workflows/CD-BE-Test-heroku.yml
Labels: 🏗️ build, 👫 common, 🏭 Infra

#164 [SDR-292] BE : 리뷰 추천목록 로직 수정
  be/src/main/java/com/jjikmuk/sikdorak/review/repository/ReviewRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/review/service/ReviewService.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewsRecommendIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/tool/DatabaseConfigurator.java
Labels: 🤖 BE, ♻️ refactor

#165 [SDR-293] common : FE-prod 배포 시 Review deployments 하도록 기능 추가
  .github/workflows/CD-FE.yml
Labels: 🌐 FE, 👫 common, 🏭 Infra

#166 [SDR-294] common : fix: jib 버전업
  be/build.gradle
Labels: 🤖 BE, 🐛 bug, 👫 common, 🏭 Infra

#167 SDR-294 common : GitHub Actions에서 ECR login 로그인 추가
  .github/workflows/CD-BE-ECS.yml
Labels: 👫 common, 🏭 Infra

#168 [SDR-294] common : jib option 변경 - ECR URL
  .github/workflows/CD-BE-ECS.yml
  be/config-docker/profile_prod.gradle
Labels: 👫 common, 🏭 Infra

#156 [SDR-280] BE : 가게 도메인 필수값 변경 리펙토링
  be/src/main/java/com/jjikmuk/sikdorak/store/domain/ContactNumber.java
  be/src/main/java/com/jjikmuk/sikdorak/store/domain/StoreLocation.java
  be/src/main/java/com/jjikmuk/sikdorak/store/domain/StoreName.java
  be/src/test/java/com/jjikmuk/sikdorak/unittest/store/domain/ContactNumberTest.java
Labels: 🤖 BE, ♻️ refactor

#169 [SDR-295] common : path error task-definition.json
  .github/workflows/CD-BE-ECS.yml
Labels: 🐛 bug, 👫 common, 🏭 Infra

#170 [SDR-272] 가게 상세정보 조회 API 구현
  be/src/docs/asciidoc/store/store.adoc
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/review/repository/ReviewRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/StoreController.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/response/StoreDetailResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/store/domain/Store.java
  be/src/main/java/com/jjikmuk/sikdorak/store/service/StoreService.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/store/StoreDetailDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/store/StoreSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/store/StoreSearchDetailIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/tool/DataGenerator.java
Labels: 🤖 BE, ✨ feature

#171 [SDR-300] common : Route53 적용 후 프로젝트 아키텍처 그림 수정
  README.md
Labels: 📝 docs, 👫 common, 🏭 Infra

#173 [SDR-273] BE : 가게의 리뷰 목록 조회 API 구현
  be/src/docs/asciidoc/store/store.adoc
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/review/repository/ReviewRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/review/service/ReviewService.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/StoreController.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/store/StoreReviewsSearchByStoreIdDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/store/StoreSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewsSearchByStoreIdIntegrationTest.java
Labels: 🤖 BE, ✨ feature

#175 [SDR-302] BE : 가독성을 위한 REST Docs 리팩터링
  be/src/docs/asciidoc/auth/auth.adoc
  be/src/docs/asciidoc/aws/s3.adoc
  be/src/docs/asciidoc/comment/comment.adoc
  be/src/docs/asciidoc/index.adoc
  be/src/docs/asciidoc/review/review.adoc
  be/src/docs/asciidoc/store/store.adoc
  be/src/docs/asciidoc/user/user.adoc
Labels: 🤖 BE, 📝 docs, ♻️ refactor

#174 [SDR-241] BE : 지도에서 위치기반 가게목록 조회 API
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/ExceptionCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/StoreController.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/request/UserLocationInfoRequest.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/response/StoreListByRadiusResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/response/StoreRadiusSearchResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/store/domain/UserLocationInfo.java
  be/src/main/java/com/jjikmuk/sikdorak/store/exception/InvalidUserLocationException.java
  be/src/main/java/com/jjikmuk/sikdorak/store/repository/StoreRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/store/service/StoreService.java
  be/src/main/java/com/jjikmuk/sikdorak/store/service/dto/UserLocationBasedMaxRange.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/store/StoreSearchByRadiusDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/store/StoreSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/store/StoreSearchByRadiusIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/tool/DatabaseConfigurator.java
  be/src/test/java/com/jjikmuk/sikdorak/unittest/store/domain/UserLocationInfoTest.java
Labels: 🤖 BE, ✨ feature

#176 [SDR-119] BE : 관리자만 가게관련 요청을 할 수 있도록 변경
  be/src/docs/asciidoc/store/store.adoc
  be/src/main/java/com/jjikmuk/sikdorak/common/aop/AdminOnly.java
  be/src/main/java/com/jjikmuk/sikdorak/common/aop/ValidateUserLoginAspect.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/ExceptionCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/StoreController.java
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/controller/Authority.java
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/controller/LoginUser.java
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/controller/OAuthUserArgumentResolver.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/Authority.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/User.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/UserRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/exception/InvalidAuthorityException.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/store/StoreCreateDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/store/StoreModifyDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/store/StoreRemoveDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/comment/CommentCreateIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewInsertIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewLikeIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewModifyIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewRemoveIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewSearchIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewsRecommendIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/auth/OAuthArgumentResolverIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserDeleteIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserFollowUnfollowIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserFollowersSearchByUserIdIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserFollowingsSearchByUserIdIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserModifyIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserReviewsSearchByUserIdIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserSearchProfileIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserSearchSelfProfileIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/tool/DataGenerator.java
  be/src/test/java/com/jjikmuk/sikdorak/tool/DatabaseConfigurator.java
  be/src/test/java/com/jjikmuk/sikdorak/unittest/user/user/domain/UserTest.java
Labels: 🤖 BE, ✨ feature

#177 [SDR-306] BE: 런타임에 NullPointerException 이 발생할 수 있는 부분 개선
  be/src/main/java/com/jjikmuk/sikdorak/common/controller/CursorPageableArgumentResolver.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/ExceptionCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/SikdorakServerError.java
Labels: 🤖 BE, ✨ feature

#179 [SDR-304] FE : 지도 페이지 가게 목록 조회 API 연동
  fe/.eslintrc
  fe/public/index.html
  fe/src/@types/import-svg.d.ts
  fe/src/App.tsx
  fe/src/assets/Logo.png
  fe/src/components/Common/Feeds/Feeds.tsx
  fe/src/components/Common/GuideText/GuideText.tsx
  fe/src/components/Common/Header/CommonHeader.tsx
  fe/src/components/Common/Logo/Logo.tsx
  fe/src/components/Common/Modal/Modal.styled.ts
  fe/src/components/Map/MapComponent.styled.ts
  fe/src/components/Map/MapComponent.tsx
  fe/src/components/Map/Store/Store.styled.tsx
  fe/src/components/Map/Store/Store.tsx
  fe/src/components/Map/Stores/Stores.styled.ts
  fe/src/components/Map/Stores/Stores.tsx
  fe/src/components/ReviewDetail/Menu/Menu.tsx
  fe/src/components/ReviewList/Feed/Feed.tsx
  fe/src/components/ReviewWrite/RegistrationBtn/RegistrationBtn.tsx
  fe/src/components/ReviewWrite/RestaurantSearch/RestaurantSearch.styled.ts
  fe/src/components/ReviewWrite/RestaurantSearch/RestaurantSearch.tsx
  fe/src/components/ReviewWrite/SearchResult/SearchResult.tsx
  fe/src/components/ReviewWrite/SearchResultList/SearchResultList.tsx
  fe/src/components/ReviewWrite/Tag/TagList/TagList.styled.ts
  fe/src/components/ReviewWrite/Tag/TagList/TagList.tsx
  fe/src/components/StoreDetail/StoreInfo/StoreInfo.tsx
  fe/src/components/StoreDetail/StorePictures/StorePictures.tsx
  fe/src/constants/dummyData.ts
  fe/src/constants/size.ts
  fe/src/context/ReviewWriteProvider.tsx
  fe/src/context/ReviewsProvider.tsx
  fe/src/context/reviewWriteProvider.tsx
  fe/src/hooks/useAuth.tsx
  fe/src/hooks/useReviews.tsx
  fe/src/hooks/useSearchBar.tsx
  fe/src/hooks/useStores.ts
  fe/src/pages/Login/Login.tsx
  fe/src/pages/Map/Map.styled.ts
  fe/src/pages/Map/Map.tsx
  fe/src/pages/ReviewDetail/ReviewDetail.tsx
  fe/src/pages/ReviewList/ReviewList.tsx
  fe/src/pages/ReviewWrite/ReviewWrite.tsx
  fe/src/pages/StoreDetail/StoreDetail.styled.ts
  fe/src/pages/StoreDetail/StoreDetail.tsx
  fe/src/pages/UserDetail/UserDetail.tsx
  fe/src/pages/UserDetail/userDetail.tsx
Labels: 🌐 FE, ✨ feature, 💄 style

#178 [SDR-305] common : 운영 서버 web, api docs 링크 뱃지 추가
  README.md
Labels: 📝 docs, 👫 common

#182 [SDR-311] common : .env 파일 생성 위치 변경 / CD 작동 범위 수정
  .github/workflows/CD-BE-ECS.yml
  .github/workflows/CD-FE.yml
  .github/workflows/CI-FE.yml
Labels: 🌐 FE, 🐛 bug, 👫 common, 🏭 Infra

#183 [SDR-309] FE : 테스트 코드 수정
  fe/src/App.test.tsx
  fe/src/components/Common/Logo/Logo.test.tsx
  fe/src/components/ReviewDetail/Menu/Menu.tsx
  fe/src/components/ReviewDetail/UserProfile/UserProfile.test.tsx
  fe/src/pages/Login/Login.test.tsx
Labels: 🌐 FE

#184 [SDR-311] common : npm build 추가
  .github/workflows/CD-FE.yml
Labels: 🌐 FE, 🐛 bug, 👫 common, 🏭 Infra

#185 [SDR-312] FE : 파일 대소문자 이슈 해결
  fe/src/context/reviewDetailProvider.tsx
  fe/src/pages/Map/Map.styled.ts
  fe/src/pages/Map/Map.tsx
  fe/src/pages/UserDetail/userDetail.styled.ts
Labels: 🌐 FE, 🐛 bug

#187 [SDR-275] FE : 작성자, 가게 클릭하면 해당 상세페이지로 이동
  fe/src/components/Map/Store/Store.styled.tsx
  fe/src/components/Map/Store/Store.tsx
  fe/src/components/ReviewDetail/Comment/Comment.styled.ts
  fe/src/components/ReviewDetail/Comment/Comment.tsx
  fe/src/components/ReviewDetail/RestaurantProfile/RestaurantProfile.tsx
  fe/src/components/ReviewDetail/UserProfile/UserProfile.tsx
  fe/src/components/ReviewList/Feed/Feed.tsx
  fe/src/components/ReviewWrite/Tag/TagList/TagList.styled.ts
  fe/src/hooks/useAuth.tsx
  fe/src/pages/ReviewDetail/ReviewDetail.tsx
Labels: 🌐 FE, ✨ feature

#186 [SDR-313] BE : 위치기반 근처 가게목록 조회 시 페이징에 last값 수정
  be/src/main/java/com/jjikmuk/sikdorak/store/service/StoreService.java
Labels: 🤖 BE, ♻️ refactor

#190 [SDR-314] FE : 리뷰 공유하기 기능 추가
  fe/src/App.tsx
  fe/src/components/ReviewList/Feed/Feed.tsx
  fe/src/hooks/useAuth.tsx
  fe/src/pages/ReivewShare/ReviewShare.tsx
  fe/src/pages/ReviewDetail/ReviewDetail.tsx
Labels: 🌐 FE, ✨ feature

#191 [SDR-314] FE : 리뷰 작성 모달창 버그 수정
  fe/src/components/ReviewWrite/Calendar/Calendar.tsx
  fe/src/components/ReviewWrite/RegistrationBtn/RegistrationBtn.tsx
  fe/src/components/ReviewWrite/Tag/TagContainer/TagContainer.tsx
  fe/src/components/ReviewWrite/Tag/TagInput/TagInput.styled.ts
  fe/src/context/ReviewWriteProvider.tsx
  fe/src/hooks/useAuth.tsx
  fe/src/pages/ReviewWrite/ReviewWrite.tsx
Labels: 🌐 FE, ✨ feature, 🐛 bug

#189 [SDR-316] BE : 댓글 조회 시 마지막 페이지일 경우 last 값을 주도록 개선
  be/src/main/java/com/jjikmuk/sikdorak/comment/repository/CommentRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/comment/service/CommentService.java
Labels: 🤖 BE, 🐛 bug

#192 [SDR-317] BE : deleted 된 데이터까지 조회할 수 있도록 countAll 메서드 생성
  be/src/main/java/com/jjikmuk/sikdorak/comment/service/CommentService.java
  be/src/main/java/com/jjikmuk/sikdorak/review/repository/ReviewRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/review/service/ReviewService.java
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/controller/OAuthUserArgumentResolver.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/repository/UserRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/service/UserService.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/auth/OAuthLoginIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserCreateIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserDeleteIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserFollowUnfollowIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserModifyIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/tool/DatabaseConfigurator.java
  be/src/test/java/com/jjikmuk/sikdorak/tool/UserDataConfigurator.java
Labels: 🤖 BE, 🐛 bug

#193 [SDR-314] FE : 지도에서 가게 안나오는 버그 수정
  fe/src/App.tsx
  fe/src/components/Map/MapComponent.styled.ts
  fe/src/components/Map/MapComponent.tsx
  fe/src/components/ReviewDetail/WriteComment/WriteComment.styled.ts
  fe/src/components/ReviewDetail/WriteComment/WriteComment.tsx
  fe/src/components/ReviewList/Feed/Feed.tsx
  fe/src/components/ReviewWrite/RestaurantSearch/RestaurantSearch.tsx
  fe/src/components/ReviewWrite/Textarea/Textarea.tsx
  fe/src/components/UserDetail/FollowButton/FollowButton.tsx
  fe/src/hooks/useStores.ts
  fe/src/pages/Map/Map.tsx
  fe/src/pages/ReviewDetail/ReviewDetail.tsx
  fe/src/pages/ReviewWrite/ReviewWrite.tsx
  fe/src/pages/UserDetail/UserDetail.tsx
Labels: 🌐 FE, ✨ feature, 🐛 bug, 💄 style

#195 [SDR-319] BE : 리뷰목록 조회 시 페이징 커서 초기화를 maxId로 하도록 수정 및 리뷰의 좋아요 정보 수정
  be/src/main/java/com/jjikmuk/sikdorak/review/controller/response/reviewdetail/ReviewDetailResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/review/repository/ReviewRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/review/service/ReviewService.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/StoreController.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewsSearchByStoreIdIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserReviewsSearchByUserIdIntegrationTest.java
Labels: 🤖 BE, 🐛 bug, 🔥 Hotfix

#196 [SDR-326] BE : CheckStyle & PMD 규칙 수정과 Code Smells 제거
  be/config-static-analyzer/checkstyle/custom-google-checkstyle.xml
  be/config-static-analyzer/pmd/custom-pmd-rules.xml
  be/src/main/java/com/jjikmuk/sikdorak/aws/service/GeneratePresignedURLService.java
  be/src/main/java/com/jjikmuk/sikdorak/comment/domain/CommentContent.java
  be/src/main/java/com/jjikmuk/sikdorak/common/CodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/aop/LogAspect.java
  be/src/main/java/com/jjikmuk/sikdorak/common/aop/ValidateUserLoginAspect.java
  be/src/main/java/com/jjikmuk/sikdorak/common/config/feignclient/FeignClientKakaoApiErrorConfiguration.java
  be/src/main/java/com/jjikmuk/sikdorak/common/config/feignclient/FeignClientOAuthErrorConfiguration.java
  be/src/main/java/com/jjikmuk/sikdorak/common/config/feignclient/KakaoAccountResponseDeserializer.java
  be/src/main/java/com/jjikmuk/sikdorak/common/controller/CursorPageableArgumentResolver.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/ExceptionCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/response/CommonResponseEntity.java
  be/src/main/java/com/jjikmuk/sikdorak/review/controller/ReviewController.java
  be/src/main/java/com/jjikmuk/sikdorak/review/controller/response/reviewdetail/ReviewDetailStoreResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Image.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/RecommendationType.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/ReviewContent.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/ReviewScore.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/ReviewVisibility.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/ReviewVisitedDate.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Tag.java
  be/src/main/java/com/jjikmuk/sikdorak/review/exception/InvalidReviewVisitedDateException.java
  be/src/main/java/com/jjikmuk/sikdorak/store/domain/Address.java
  be/src/main/java/com/jjikmuk/sikdorak/store/domain/ContactNumber.java
  be/src/main/java/com/jjikmuk/sikdorak/store/domain/StoreLocation.java
  be/src/main/java/com/jjikmuk/sikdorak/store/domain/StoreName.java
  be/src/main/java/com/jjikmuk/sikdorak/store/service/StoreService.java
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/controller/OAuthController.java
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/domain/JwtProvider.java
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/exception/ExpiredTokenException.java
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/exception/InvalidTokenException.java
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/service/OAuthService.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/controller/UserController.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/controller/response/UserDetailProfileResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/Email.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/Nickname.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/ProfileImage.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/User.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/service/UserService.java
Labels: 🤖 BE, ♻️ refactor, 💄 style

#197 [SDR-360] BE : SonarCloud 규칙 수정과 Code Smells 제거
  be/build.gradle
  be/src/main/java/com/jjikmuk/sikdorak/comment/repository/CommentRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/comment/service/CommentService.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/SikdorakRuntimeException.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Image.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Images.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/RecommendationType.java
  be/src/main/java/com/jjikmuk/sikdorak/review/repository/ReviewRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/review/service/ReviewService.java
  be/src/main/java/com/jjikmuk/sikdorak/store/domain/StoreLocation.java
  be/src/main/java/com/jjikmuk/sikdorak/store/service/KakaoPlaceApiService.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/Email.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/ProfileImage.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/store/StoreSearchDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/user/user/UserModifyDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/comment/CommentModifyIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/comment/CommentSearchIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewInsertIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewModifyIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewRemoveIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/auth/OAuthLoginIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserCreateIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/unittest/review/domain/ImageTest.java
Labels: 🤖 BE, ♻️ refactor, 💄 style

#198 [SDR-344] FE : AccountStore 생성
  fe/.eslintrc
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/components/Common/Header/CommonHeader.tsx
  fe/src/components/ReviewDetail/WriteComment/WriteComment.tsx
  fe/src/components/ReviewList/Feed/Feed.tsx
  fe/src/context/MyUserInfoProvider.tsx
  fe/src/index.tsx
  fe/src/pages/Callback/Callback.tsx
  fe/src/pages/Login/Login.tsx
  fe/src/pages/ReviewWrite/ReviewWrite.tsx
  fe/src/pages/UserDetail/UserDetail.tsx
  fe/src/stores/AccountStore.ts
  fe/tsconfig.json
Labels: 🌐 FE, ♻️ refactor
