Repository jjik-muk/sikdorak, pull requests merged in 2022-10, with the labels that each got.

#202 [SDR-362] FE : 리뷰 작성 모달 반응형 화면 구성
  fe/src/constants/size.ts
  fe/src/pages/ReviewWrite/ReviewWrite.styled.ts
  fe/src/pages/ReviewWrite/ReviewWrite.tsx
Labels: 🌐 FE, ✨ feature

#203 [SDR-328] common : 프론트 테스트 서버 구축
  .github/workflows/CD-FE-Test-Firebase.yml
  fe/firebase.json
Labels: 🏗️ build, 👫 common, 🏭 Infra

#205 [SDR-331] BE : 이미지 메타 정보 서비스 구현 (init / update)
  be/src/docs/asciidoc/image/s3.adoc
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/jjikmuk/sikdorak/aws/service/GeneratePresignedURLService.java
  be/src/main/java/com/jjikmuk/sikdorak/aws/service/response/PresignedUrlCreateResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/ExceptionCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/image/api/AwsCommandApi.java
  be/src/main/java/com/jjikmuk/sikdorak/image/command/app/AwsS3ImageService.java
  be/src/main/java/com/jjikmuk/sikdorak/image/command/app/ImageMetaDataService.java
  be/src/main/java/com/jjikmuk/sikdorak/image/command/app/ImageMetaDataServiceImpl.java
  be/src/main/java/com/jjikmuk/sikdorak/image/command/app/request/PreSignedUrlCreateRequest.java
  be/src/main/java/com/jjikmuk/sikdorak/image/command/app/response/PreSignedUrlCreateResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/image/command/domain/ImageExtension.java
  be/src/main/java/com/jjikmuk/sikdorak/image/command/domain/ImageFileName.java
  be/src/main/java/com/jjikmuk/sikdorak/image/command/domain/ImageMetaData.java
  be/src/main/java/com/jjikmuk/sikdorak/image/command/domain/ImageMetaDataRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/image/exception/DuplicateImageMetaDataException.java
  be/src/main/java/com/jjikmuk/sikdorak/image/exception/InvalidImageOriginUrlException.java
  be/src/main/java/com/jjikmuk/sikdorak/image/exception/InvalidImageSizeException.java
  be/src/main/java/com/jjikmuk/sikdorak/image/exception/InvalidImagesExtensionException.java
  be/src/main/java/com/jjikmuk/sikdorak/image/exception/NotFoundImageException.java
  be/src/main/java/com/jjikmuk/sikdorak/image/exception/NotFoundImageMetaDataException.java
  be/src/main/java/com/jjikmuk/sikdorak/review/api/ReviewCommandApi.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/InitDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/comment/CommentCreateDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/comment/CommentModifyDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/comment/CommentRemoveDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/comment/CommentSearchDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/image/PreSignedURLCreateDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/image/S3Snippet.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/review/ReviewInsertDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/review/ReviewLikeDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/review/ReviewModifyDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/review/ReviewRemoveAccecptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/review/ReviewsRecommendDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/store/StoreDetailDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/store/StoreSearchDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/user/auth/OAuthUpdateTokenDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/user/user/UserDeleteDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/user/user/UserFollowUnfollowDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/user/user/UserFollowersSearchByUserIdDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/user/user/UserFollowingsSearchByUserIdDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/user/user/UserModifyDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/user/user/UserSearchProfileDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/user/user/UserSearchSelfProfileDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/InitIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/comment/CommentCreateIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/comment/CommentModifyIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/comment/CommentRemoveIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/comment/CommentSearchIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/image/ImageMetaDataServiceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewLikeIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewModifyIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewRemoveIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/auth/OAuthArgumentResolverIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/auth/OAuthUpdateTokenIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/tool/DatabaseConfigurator.java
  be/src/test/java/com/jjikmuk/sikdorak/tool/mock/AWSMockConfig.java
  be/src/test/java/com/jjikmuk/sikdorak/unittest/aws/ImageExtensionTest.java
  be/src/test/java/com/jjikmuk/sikdorak/unittest/aws/ImageFileNameTest.java
  be/src/test/resources/images/jjikmuk.png
Labels: 🤖 BE, ✨ feature, 🧪 test

#207 [SDR-357] FE : ReviewDetail 스타일 수정
  fe/.prettierrc
  fe/src/components/Common/CommonHeader/CommonHeader.styled.ts
  fe/src/components/Common/CommonHeader/CommonHeader.tsx
  fe/src/components/Common/Feed/Feed.tsx
  fe/src/components/Common/FeedCard/FeedCard.tsx
  fe/src/components/Common/Feeds/Feeds.tsx
  fe/src/components/Common/KebabMenu/KebabMenu.styled.ts
  fe/src/components/Common/KebabMenu/KebabMenu.tsx
  fe/src/components/Map/MapComponent.tsx
  fe/src/components/ReviewDetail/Menu/Menu.tsx
  fe/src/components/ReviewDetail/TagList/TagList.styled.ts
  fe/src/components/ReviewDetail/TagList/TagList.tsx
  fe/src/components/ReviewDetail/WriteComment/WriteComment.tsx
  fe/src/components/ReviewList/Feed/Feed.tsx
  fe/src/components/ReviewWrite/RestaurantSearch/RestaurantSearch.tsx
  fe/src/components/UserDetail/FollowButton/FollowButton.tsx
  fe/src/constants/dummyData.ts
  fe/src/hooks/useAuth.tsx
  fe/src/hooks/useReviews.tsx
  fe/src/hooks/useSearchBar.tsx
  fe/src/hooks/useStores.ts
  fe/src/pages/Callback/Callback.tsx
  fe/src/pages/Login/Login.tsx
  fe/src/pages/Map/Map.tsx
  fe/src/pages/ReivewShare/ReviewShare.tsx
  fe/src/pages/ReviewDetail/ReviewDetail.styled.ts
  fe/src/pages/ReviewDetail/ReviewDetail.tsx
  fe/src/pages/ReviewList/ReviewList.tsx
  fe/src/pages/ReviewWrite/ReviewWrite.styled.ts
  fe/src/pages/ReviewWrite/ReviewWrite.tsx
  fe/src/pages/StoreDetail/StoreDetail.tsx
  fe/src/pages/UserDetail/UserDetail.styled.ts
  fe/src/pages/UserDetail/UserDetail.tsx
  fe/src/styles/GlobalStyle.ts
Labels: 🌐 FE, ✨ feature, 💄 style

#216 [SDR-370] FE : fetch 관련 함수 하나로 통일
  fe/.eslintrc
  fe/src/components/Common/CommonHeader/CommonHeader.tsx
  fe/src/components/Common/KebabMenu/KebabMenu.tsx
  fe/src/components/ReviewDetail/WriteComment/WriteComment.tsx
  fe/src/components/ReviewWrite/RegistrationBtn/RegistrationBtn.tsx
  fe/src/constants/apiPath.ts
  fe/src/constants/statusCode.ts
  fe/src/hooks/useAuth.tsx
  fe/src/hooks/useLike.ts
  fe/src/hooks/useReviews.tsx
  fe/src/hooks/useSearchBar.tsx
  fe/src/hooks/useStores.ts
  fe/src/hooks/useUploadImage.ts
  fe/src/pages/Callback/Callback.tsx
  fe/src/pages/ReivewShare/ReviewShare.tsx
  fe/src/pages/ReviewDetail/ReviewDetail.tsx
  fe/src/pages/StoreDetail/StoreDetail.tsx
  fe/src/stores/AccountStore.ts
  fe/src/stores/userStore.ts
  fe/src/utils/fetch.ts
  fe/src/utils/utils.ts
Labels: 🌐 FE, ♻️ refactor

#218 [SDR-365] FE : react-toastify 설치 및 적용
  fe/.eslintrc
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/components/Common/FeedCard/FeedCard.tsx
  fe/src/components/Common/GuideText/GuideText.tsx
  fe/src/components/ReviewWrite/Calendar/Calendar.tsx
  fe/src/components/ReviewWrite/ImgUpload/ImgUpload.tsx
  fe/src/components/ReviewWrite/RegistrationBtn/RegistrationBtn.tsx
  fe/src/constants/message.ts
  fe/src/hooks/useAuth.tsx
  fe/src/hooks/useLike.ts
  fe/src/stores/AccountStore.ts
  fe/src/utils/toast.ts
Labels: 🌐 FE, ✨ feature

#219 [SDR-392] fix: ReviewList 무한 API 요청 해결
  fe/src/pages/ReviewList/ReviewList.tsx
Labels: 🌐 FE, 🐛 bug

#220 [SDR-396] feat: 로그아웃 기능 추가
  fe/src/components/Common/CommonHeader/CommonHeader.styled.ts
  fe/src/components/Common/CommonHeader/CommonHeader.tsx
Labels: 🌐 FE, ✨ feature

#222 [SDR-393] FE : 리뷰 수정 기능 추가
  fe/src/components/Common/CommonHeader/CommonHeader.tsx
  fe/src/components/Common/Feeds/Feeds.styled.ts
  fe/src/components/Common/KebabMenu/KebabMenu.tsx
  fe/src/components/ReviewWrite/ImgUpload/ImgUpload.tsx
  fe/src/components/ReviewWrite/RegistrationBtn/RegistrationBtn.tsx
  fe/src/components/ReviewWrite/Tag/TagInput/TagInput.tsx
  fe/src/context/ReviewWriteProvider.tsx
  fe/src/hooks/useUploadImage.ts
  fe/src/pages/ReviewWrite/ReviewWrite.styled.ts
  fe/src/pages/ReviewWrite/ReviewWrite.tsx
  fe/src/request/request.ts
Labels: 🌐 FE, ✨ feature

#224 [SDR-398] fix: 메인페이지 첫 진입 시 비로그인 상태로 fetch 하는 버그
  fe/src/hooks/useReviews.tsx
  fe/src/pages/ReviewList/ReviewList.tsx
  fe/src/pages/StoreDetail/StoreDetail.tsx
  fe/src/pages/UserDetail/UserDetail.tsx
Labels: 🌐 FE, 🐛 bug

#225 [SDR-394] FE : 댓글 수정 기능 추가
  fe/src/components/ReviewDetail/Comment/Comment.tsx
  fe/src/pages/ReviewDetail/ReviewDetail.tsx
Labels: 🌐 FE, ✨ feature

#226 [SDR-395] feat: 댓글 삭제 기능 추가
  fe/src/components/ReviewDetail/Comment/Comment.tsx
  fe/src/pages/ReviewDetail/ReviewDetail.tsx
Labels: 🌐 FE, ✨ feature

#227 [SDR-400] FE : 지도에서 가게 검색 안되는 버그 수정
  fe/src/components/Map/MapComponent.tsx
  fe/src/components/Map/Store/Store.tsx
  fe/src/pages/Map/Map.tsx
  fe/src/styles/zIndex.ts
Labels: 🌐 FE, ✨ feature, 🐛 bug

#228 [SDR-401] FE : 리뷰 작성의 contents가 길어도 식당 검색 가능하게 수정
  fe/src/components/ReviewWrite/RestaurantSearch/RestaurantSearch.styled.ts
  fe/src/components/ReviewWrite/Textarea/Textarea.tsx
Labels: 🌐 FE, 🐛 bug

#229 [SDR-402] FE : 평점 입력 안됐을 경우 리뷰 게시 불가 및 경고 문구 표시
  fe/src/components/ReviewWrite/RegistrationBtn/RegistrationBtn.tsx
Labels: 🌐 FE, 🐛 bug

#230 [SDR-403] FE : 리뷰 공유 버그 수정
  fe/src/components/Common/FeedCard/FeedCard.tsx
  fe/src/pages/ReivewShare/ReviewShare.tsx
Labels: 🌐 FE, 🐛 bug

#232 [SDR-408] BE - 데이터가 없는 경우 isLast값이 false로 나오는 버그 수정
  be/src/main/java/com/jjikmuk/sikdorak/review/command/domain/ReviewRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/review/query/ReviewDao.java
  be/src/main/java/com/jjikmuk/sikdorak/store/command/domain/StoreRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/store/query/StoreDao.java
Labels: 🤖 BE, 🐛 bug

#233 [SDR-243] BE - 위치기반 유저의 리뷰목록 조회 API
  be/src/docs/asciidoc/user/user.adoc
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/ExceptionCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/review/command/domain/ReviewRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/review/query/ReviewDao.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/api/UserQueryApi.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/user/user/UserReviewsSearchByRadiusDocumentationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/user/user/UserSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserReviewsSearchByRadiusIntegrationTest.java
Labels: 🤖 BE, ✨ feature
