Repository jjik-muk/sikdorak, pull requests merged in 2022-11, with the labels that each got.

#235 [SDR-410] FE : 위치 기반 유저 리뷰 검색 기능 추가
  fe/.eslintrc
  fe/src/components/Common/Feeds/Feeds.styled.ts
  fe/src/components/Map/MapComponent.styled.ts
  fe/src/components/Map/MapComponent.tsx
  fe/src/components/Map/RestaurantListTab/RestaurantListTab.tsx
  fe/src/components/Map/UserReviewTab/UserReviewTab.tsx
  fe/src/constants/statusCode.ts
  fe/src/hooks/useReviewsBasedLocation.ts
  fe/src/hooks/useStores.ts
  fe/src/pages/Map/Map.styled.ts
  fe/src/pages/Map/Map.tsx
  fe/src/styles/color.ts
  fe/src/utils/utils.ts
Labels: 🌐 FE, ✨ feature, ♻️ refactor

#234 [SDR-413] BE - 지도맵에서 유저의 리뷰목록 조회 시 가게의 위치 정보를 담은 Dto 추가 및 패키지 추가
  be/src/docs/asciidoc/user/user.adoc
  be/src/main/java/com/jjikmuk/sikdorak/review/query/ReviewDao.java
  be/src/main/java/com/jjikmuk/sikdorak/review/query/response/ReviewListForMapResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/review/query/response/reviewdetail/map/ReviewDetailForMapResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/review/query/response/reviewdetail/map/ReviewDetailStoreForMapResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/api/UserQueryApi.java
  be/src/test/java/com/jjikmuk/sikdorak/documentationtest/user/user/UserSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserReviewsSearchByRadiusIntegrationTest.java
Labels: 🤖 BE, ♻️ refactor

#237 [SDR-415] fix: 지도 페이지 피드 부분 짤림 현상 수정
  fe/src/pages/Map/Map.styled.ts
Labels: 🌐 FE, 🐛 bug

#236 [SDR-414] BE 공백 전화번호는 예외발생하지 않도록 수정
  be/src/main/java/com/jjikmuk/sikdorak/store/command/domain/StoreContactNumber.java
  be/src/test/java/com/jjikmuk/sikdorak/unittest/store/domain/StoreContactNumberTest.java
Labels: 🤖 BE, 🔥 Hotfix

#238 [SDR-416] feat: 댓글 관련 로직 분리, 댓글 작성 후 다시 fetch
  fe/src/components/ReviewDetail/WriteComment/WriteComment.tsx
  fe/src/hooks/useComment.ts
  fe/src/pages/ReviewDetail/ReviewDetail.tsx
  fe/src/stores/AccountStore.ts
Labels: 🌐 FE, ✨ feature

#239 [SDR-417] feat: 태그에 한글, 영어, 숫자만 사용 가능하게 변경
  fe/src/components/ReviewWrite/Tag/TagInput/TagInput.tsx
Labels: 🌐 FE, ✨ feature

#241 [SDR-418] FE : 공통 헤더의 로그아웃 버튼, 케밥 메뉴 버튼이 다른 영역에 가려지는 버그
  fe/src/components/Common/KebabMenu/KebabMenu.styled.ts
  fe/src/stores/userStore.ts
  fe/src/styles/zIndex.ts
  fe/src/utils/fetch.ts
Labels: 🌐 FE, 🐛 bug

#242 [SDR-421] FE : 리뷰 추가, 수정, 삭제 후 리로드
  fe/src/components/Common/CommonHeader/CommonHeader.tsx
  fe/src/components/Common/KebabMenu/KebabMenu.tsx
  fe/src/components/Common/Portal/Portal.styled.ts
  fe/src/components/ReviewDetail/WriteComment/WriteComment.tsx
  fe/src/components/ReviewWrite/RegistrationBtn/RegistrationBtn.tsx
  fe/src/hooks/useComment.ts
  fe/src/hooks/useReviews.tsx
  fe/src/pages/ReviewWrite/ReviewWrite.tsx
  fe/src/styles/zIndex.ts
  fe/src/utils/utils.ts
Labels: 🌐 FE, ✨ feature
