Repository jjik-muk/sikdorak, pull requests merged in 2022-08, with the labels that each got.

#37 [BE/fix] Restdoc 테스트가 특정 상황에 실패하는 이슈 수정
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/InitAcceptanceTest.java
Labels: 🤖 BE, 🐛 bug, 🧪 test

#39 [FE/feat] 리뷰 작성 페이지 레이아웃
  fe/.eslintrc
  fe/package-lock.json
  fe/package.json
  fe/src/@types/import-svg.d.ts
  fe/src/App.tsx
  fe/src/assets/DownArrow.svg
  fe/src/assets/Photo.svg
  fe/src/assets/Star.svg
  fe/src/assets/UpArrow.svg
  fe/src/common/Icon.tsx
  fe/src/common/Modal/Modal.styled.ts
  fe/src/common/Modal/Modal.tsx
  fe/src/common/Portal/Portal.tsx
  fe/src/components/BoxContainer/BoxContainer.styled.ts
  fe/src/components/BoxContainer/BoxContainer.tsx
  fe/src/components/Calendar/Calendar.styled.ts
  fe/src/components/Calendar/Calendar.tsx
  fe/src/components/ImgUpload/Button/Button.styled.ts
  fe/src/components/ImgUpload/Button/Button.test.tsx
  fe/src/components/ImgUpload/Button/Button.tsx
  fe/src/components/ImgUpload/ImgUpload.styled.ts
  fe/src/components/ImgUpload/ImgUpload.test.tsx
  fe/src/components/ImgUpload/ImgUpload.tsx
  fe/src/components/Login/LoginInput/LoginInput.styled.ts
  fe/src/components/PostScope/PostScope.styled.ts
  fe/src/components/PostScope/PostScope.test.tsx
  fe/src/components/PostScope/PostScope.tsx
  fe/src/components/Profile/Profile.styled.ts
  fe/src/components/Profile/Profile.test.tsx
  fe/src/components/Profile/Profile.tsx
  fe/src/components/RestaurantSearch/RestaurantSearch.styled.ts
  fe/src/components/RestaurantSearch/RestaurantSearch.test.tsx
  fe/src/components/RestaurantSearch/RestaurantSearch.tsx
  fe/src/components/SelectDay/SelectDay.styled.ts
  fe/src/components/SelectDay/SelectDay.tsx
  fe/src/components/StarIcon/StarIcon.styled.ts
  fe/src/components/StarIcon/StarIcon.tsx
  fe/src/components/StarRating/StarRating.styled.ts
  fe/src/components/StarRating/StarRating.tsx
  fe/src/components/Tag/TagContainer/TagContainer.styled.ts
  fe/src/components/Tag/TagContainer/TagContainer.tsx
  fe/src/components/Tag/TagInput/TagInput.styled.ts
  fe/src/components/Tag/TagInput/TagInput.tsx
  fe/src/components/Tag/TagItem/TagItem.styled.ts
  fe/src/components/Tag/TagItem/TagItem.tsx
  fe/src/components/Textarea/Textarea.styled.ts
  fe/src/components/Textarea/Textarea.test.tsx
  fe/src/components/Textarea/Textarea.tsx
  fe/src/components/WriteRating/WriteRating.styled.ts
  fe/src/components/WriteRating/WriteRating.tsx
  fe/src/constants/size.ts
  fe/src/index.tsx
  fe/src/pages/ReviewWrite/ReviewWrite.styled.ts
  fe/src/pages/ReviewWrite/ReviewWrite.tsx
Labels: 🌐 FE, ✨ feature

#38 [BE] 공통으로 사용할 통합테스트와 TestContainers 적용
  be/build.gradle
  be/src/main/java/com/jjikmuk/sikdorak/review/controller/request/ReviewInsertRequest.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Review.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/ReviewVisitedDate.java
  be/src/main/java/com/jjikmuk/sikdorak/review/service/ReviewService.java
  be/src/test/java/com/jjikmuk/sikdorak/common/DatabaseConfigurator.java
  be/src/test/java/com/jjikmuk/sikdorak/common/MysqlTestContainer.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/InitIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewInsertIntegrationTest.java
  be/src/test/resources/application.yml
  be/src/test/resources/logback-test.xml
Labels: 🤖 BE, ✨ feature, 🧪 test, ♻️ refactor

#41 [BE] API 문서화 도구를 SwaggerUI 에서 Asciidoc 변경
  be/build.gradle
  be/src/docs/asciidoc/index.adoc
  be/src/docs/asciidoc/review/review.adoc
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/InitAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/ReviewAcceptanceTest.java
  be/src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-fields.snippet
Labels: 🤖 BE, 🏗️ build, 📝 docs

#42 [BE] 유저 카카오 로그인 API
  be/build.gradle
  be/src/main/java/com/jjikmuk/sikdorak/SikdorakApplication.java
  be/src/main/java/com/jjikmuk/sikdorak/auth/controller/OAuthController.java
  be/src/main/java/com/jjikmuk/sikdorak/auth/controller/response/JwtTokenResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/auth/controller/response/KakaoAccountResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/auth/controller/response/OAuthTokenResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/auth/domain/JwtProvider.java
  be/src/main/java/com/jjikmuk/sikdorak/auth/exception/InvalidUserNicknameException.java
  be/src/main/java/com/jjikmuk/sikdorak/auth/exception/InvalidUserProfileImageUrlException.java
  be/src/main/java/com/jjikmuk/sikdorak/auth/exception/KakaoApiException.java
  be/src/main/java/com/jjikmuk/sikdorak/auth/service/OAuthApiClient.java
  be/src/main/java/com/jjikmuk/sikdorak/auth/service/OAuthService.java
  be/src/main/java/com/jjikmuk/sikdorak/auth/service/OAuthTokenClient.java
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/config/feignclient/FeignClientErrorConfiguration.java
  be/src/main/java/com/jjikmuk/sikdorak/common/config/feignclient/FeignClientHeaderConfiguration.java
  be/src/main/java/com/jjikmuk/sikdorak/common/config/feignclient/KakaoAccountResponseDeserializer.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/ExceptionCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/properties/JwtProperties.java
  be/src/main/java/com/jjikmuk/sikdorak/common/properties/KakaoProperties.java
  be/src/main/java/com/jjikmuk/sikdorak/common/util/feignclient/FeignClientResponseUtils.java
  be/src/main/java/com/jjikmuk/sikdorak/user/domain/Email.java
  be/src/main/java/com/jjikmuk/sikdorak/user/domain/Nickname.java
  be/src/main/java/com/jjikmuk/sikdorak/user/domain/ProfileImage.java
  be/src/main/java/com/jjikmuk/sikdorak/user/domain/User.java
  be/src/main/java/com/jjikmuk/sikdorak/user/domain/UserRespository.java
  be/src/main/java/com/jjikmuk/sikdorak/user/exception/DuplicateUserException.java
  be/src/main/java/com/jjikmuk/sikdorak/user/exception/InvalidUserEmailException.java
  be/src/main/java/com/jjikmuk/sikdorak/user/service/UserService.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/LoginAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/UserCreateIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/user/domain/EmailTest.java
  be/src/test/java/com/jjikmuk/sikdorak/user/domain/NicknameTest.java
  be/src/test/java/com/jjikmuk/sikdorak/user/domain/ProfileImageTest.java
  be/src/test/java/com/jjikmuk/sikdorak/user/domain/UserTest.java
  be/src/test/resources/application.yml
Labels: 🤖 BE, ✨ feature

#44 [BE/refactor] 공통으로 인수/통합 테스트 구조와 API 문서 자동화
  be/src/docs/asciidoc/index.adoc
  be/src/docs/asciidoc/review/review.adoc
  be/src/main/java/com/jjikmuk/sikdorak/review/controller/request/ReviewInsertRequest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/DocumentFormatGenerator.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/InitAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/ReviewAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/review/ReviewInsertAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/review/ReviewSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/common/DatabaseConfigurator.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/InitIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewInsertIntegrationTest.java
  be/src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-fields.snippet
Labels: 🤖 BE, 📝 docs, 🧪 test, ♻️ refactor

#47 [common] BE팀 - CI를 활용한 자동 정적 분석과 코드리뷰 제안 기능
  .github/workflows/CI-BE.yml
  .sonarcloud.properties
  be/build.gradle
  infra/be/README.md
  infra/be/heroku/.terraform.lock.hcl
  infra/be/heroku/infra.tf
  infra/be/heroku/provider.tf
  infra/be/heroku/variables.tf
  infra/be/sonarcloud/.terraform.lock.hcl
  infra/be/sonarcloud/infra.tf
  infra/be/sonarcloud/provider.tf
  infra/be/sonarcloud/varibales.tf
Labels: 🤖 BE, 👫 common, 🏭 Infra

#48 [BE] CI에서 BE 빌드 시 jacoco 문서 생성
  .github/workflows/CI-BE.yml
Labels: 🤖 BE, 📝 docs, 👫 common

#49 [BE] CI-BE 적용 범위 수정
  .github/workflows/CI-BE.yml
Labels: 🤖 BE, 👫 common

#46 [BE/feat] 특정 음식점을 상세 조회할 수 있는 API 추가
  be/src/docs/asciidoc/index.adoc
  be/src/docs/asciidoc/store/store.adoc
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/ExceptionCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/StoreController.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/response/StoreFindResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/store/domain/Address.java
  be/src/main/java/com/jjikmuk/sikdorak/store/domain/ContactNumber.java
  be/src/main/java/com/jjikmuk/sikdorak/store/domain/Store.java
  be/src/main/java/com/jjikmuk/sikdorak/store/domain/StoreLocation.java
  be/src/main/java/com/jjikmuk/sikdorak/store/domain/StoreName.java
  be/src/main/java/com/jjikmuk/sikdorak/store/exception/InvalidAddressException.java
  be/src/main/java/com/jjikmuk/sikdorak/store/exception/InvalidContactNumberException.java
  be/src/main/java/com/jjikmuk/sikdorak/store/exception/InvalidStoreLocationException.java
  be/src/main/java/com/jjikmuk/sikdorak/store/exception/InvalidStoreNameException.java
  be/src/main/java/com/jjikmuk/sikdorak/store/repository/StoreRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/store/service/StoreService.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/InitAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/StoreAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/store/StoreSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/common/DatabaseConfigurator.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/store/StoreFindIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/store/domain/AddressTest.java
  be/src/test/java/com/jjikmuk/sikdorak/store/domain/ContactNumberTest.java
  be/src/test/java/com/jjikmuk/sikdorak/store/domain/StoreLocationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/store/domain/StoreNameTest.java
Labels: 🤖 BE, ✨ feature

#50 [BE/fix] CI-BE 적용 범위 수정
  .github/workflows/CI-BE.yml
Labels: 🤖 BE, 📝 docs, 👫 common

#54 [BE] WireMock을 사용한 로그인 인수테스트 작성
  be/build.gradle
  be/src/docs/asciidoc/auth/auth.adoc
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/jjikmuk/sikdorak/auth/service/OAuthApiClient.java
  be/src/main/java/com/jjikmuk/sikdorak/auth/service/OAuthService.java
  be/src/main/java/com/jjikmuk/sikdorak/auth/service/OAuthTokenClient.java
  be/src/main/java/com/jjikmuk/sikdorak/common/config/feignclient/KakaoAccountResponseDeserializer.java
  be/src/main/java/com/jjikmuk/sikdorak/user/domain/ProfileImage.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/DocumentFormatGenerator.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/LoginAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/auth/OAuthAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/auth/OAuthSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/store/StoreSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/common/DatabaseConfigurator.java
  be/src/test/java/com/jjikmuk/sikdorak/common/mock/OAuthMocks.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/UserCreateIntegrationTest.java
  be/src/test/resources/application.yml
  be/src/test/resources/payload/get-token-response.json
  be/src/test/resources/payload/get-user-info-response.json
Labels: 🤖 BE, ✨ feature

#55 [BE/performance] 테스트 실행 속도 개선(테스트 컨테이너 재활용)
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/InitAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/common/MysqlTestContainer.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/InitIntegrationTest.java
Labels: 🤖 BE, 🏗️ build, ♻️ refactor

#64 [BE/feat] 액세스 토큰 재발급 API
  be/src/docs/asciidoc/auth/auth.adoc
  be/src/main/java/com/jjikmuk/sikdorak/auth/controller/OAuthController.java
  be/src/main/java/com/jjikmuk/sikdorak/auth/controller/response/SikdorakAccessToken.java
  be/src/main/java/com/jjikmuk/sikdorak/auth/domain/JwtProvider.java
  be/src/main/java/com/jjikmuk/sikdorak/auth/domain/JwtTokenPair.java
  be/src/main/java/com/jjikmuk/sikdorak/auth/exception/InvalidTokenException.java
  be/src/main/java/com/jjikmuk/sikdorak/auth/exception/OAuthServerException.java
  be/src/main/java/com/jjikmuk/sikdorak/auth/service/OAuthService.java
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/config/feignclient/FeignClientOAuthErrorConfiguration.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/ExceptionCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/response/CommonResponseEntity.java
  be/src/main/java/com/jjikmuk/sikdorak/user/domain/Nickname.java
  be/src/main/java/com/jjikmuk/sikdorak/user/domain/ProfileImage.java
  be/src/main/java/com/jjikmuk/sikdorak/user/domain/UserRespository.java
  be/src/main/java/com/jjikmuk/sikdorak/user/exception/InvalidUserNicknameException.java
  be/src/main/java/com/jjikmuk/sikdorak/user/exception/InvalidUserProfileImageUrlException.java
  be/src/main/java/com/jjikmuk/sikdorak/user/exception/UserNotFoundException.java
  be/src/main/java/com/jjikmuk/sikdorak/user/service/UserService.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/auth/OAuthLoginAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/auth/OAuthSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/auth/OAuthUpdateTokenAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/user/domain/NicknameTest.java
  be/src/test/java/com/jjikmuk/sikdorak/user/domain/ProfileImageTest.java
Labels: 🤖 BE, ✨ feature

#68 SDR-46 BE - 가게 등록 API 구현
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/StoreController.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/request/StoreInsertRequest.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/response/StoreFindResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/response/StoreSearchResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/store/service/StoreService.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/store/StoreInsertAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/store/StoreSearchAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/store/StoreSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/store/StoreInsertIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/store/StoreSearchIntegrationTest.java
Labels: 🤖 BE, ✨ feature

#74 SDR-131 공통 헤더 컴포넌트
  fe/src/assets/Alarm.svg
  fe/src/assets/Home.svg
  fe/src/assets/Map.svg
  fe/src/assets/PostBtn.svg
  fe/src/assets/Profile.svg
  fe/src/assets/SearchBtn.svg
  fe/src/common/Icon.tsx
  fe/src/common/IconButton/IconButton.styled.ts
  fe/src/common/IconButton/IconButton.tsx
  fe/src/common/Portal/Portal.tsx
  fe/src/components/Common/CommonHeader.styled.ts
  fe/src/components/Common/CommonHeader.tsx
  fe/src/components/Common/Header.tsx
  fe/src/pages/Login/Login.tsx
  fe/src/pages/ReviewDetail/ReviewDetail.styled.ts
  fe/src/pages/ReviewDetail/ReviewDetail.tsx
Labels: 🌐 FE, ✨ feature

#69 SDR-64 로그인한 유저의 리뷰 생성 API 기능
  be/src/main/java/com/jjikmuk/sikdorak/review/controller/ReviewController.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Review.java
  be/src/main/java/com/jjikmuk/sikdorak/review/service/ReviewService.java
  be/src/main/java/com/jjikmuk/sikdorak/store/service/StoreService.java
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/service/OAuthService.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/service/UserService.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewInsertIntegrationTest.java
Labels: 🤖 BE, 🧪 test, ♻️ refactor

#75 SDR-120 인터셉터 대신 AOP 적용
  be/src/main/java/com/jjikmuk/sikdorak/SikdorakApplication.java
  be/src/main/java/com/jjikmuk/sikdorak/common/aop/LogAspect.java
  be/src/main/java/com/jjikmuk/sikdorak/common/aop/UserOnly.java
  be/src/main/java/com/jjikmuk/sikdorak/common/aop/ValidateUserLoginAspect.java
  be/src/main/java/com/jjikmuk/sikdorak/common/config/WebMvcConfig.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/ExceptionCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/review/controller/ReviewController.java
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/controller/LoginUser.java
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/controller/OAuthUserArgumentResolver.java
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/exception/NeedLoginException.java
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/interceptor/OAuthUserInterceptor.java
  be/src/test/java/com/jjikmuk/sikdorak/common/config/WebMvcConfigTest.java
Labels: 🤖 BE, ♻️ refactor

#76 SDR-128 OAuthClient에 ErrorConfiguration 추가
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/service/OAuthApiClient.java
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/service/OAuthTokenClient.java
Labels: 🤖 BE, ♻️ refactor

#77 SDR-116 가게 수정 API 구현
  be/src/docs/asciidoc/index.adoc
  be/src/docs/asciidoc/store/store.adoc
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/response/CommonResponseEntity.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/StoreController.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/request/StoreCreateRequest.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/request/StoreModifyRequest.java
  be/src/main/java/com/jjikmuk/sikdorak/store/domain/Store.java
  be/src/main/java/com/jjikmuk/sikdorak/store/service/StoreService.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/store/StoreCreateAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/store/StoreModifyAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/store/StoreSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/store/StoreCreateIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/store/StoreModifyIntegrationTest.java
Labels: 🤖 BE, ✨ feature

#78 SDR-122 리뷰 수정 API 구현
  be/src/docs/asciidoc/review/review.adoc
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/ExceptionCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/GlobalExceptionHandler.java
  be/src/main/java/com/jjikmuk/sikdorak/review/controller/ReviewController.java
  be/src/main/java/com/jjikmuk/sikdorak/review/controller/request/ReviewCreateRequest.java
  be/src/main/java/com/jjikmuk/sikdorak/review/controller/request/ReviewModifyRequest.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Review.java
  be/src/main/java/com/jjikmuk/sikdorak/review/exception/NotFoundReviewException.java
  be/src/main/java/com/jjikmuk/sikdorak/review/service/ReviewService.java
  be/src/main/java/com/jjikmuk/sikdorak/store/exception/NotFoundStoreException.java
  be/src/main/java/com/jjikmuk/sikdorak/store/service/StoreService.java
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/service/OAuthService.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/exception/NotFoundUserException.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/exception/UnauthorizedUserException.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/service/UserService.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/review/ReviewInsertAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/review/ReviewModifyAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/review/ReviewSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/store/StoreCreateAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/store/StoreModifyAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/store/StoreSearchAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/user/auth/OAuthUpdateTokenAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/common/DatabaseConfigurator.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewInsertIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewModifyIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/auth/OAuthArgumentResolverIntegrationTest.java
Labels: 🤖 BE, ✨ feature, 🧪 test

#79 SDR-34 유저 프로필 업데이트 기능
  be/src/docs/asciidoc/index.adoc
  be/src/docs/asciidoc/user/user.adoc
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/controller/UserController.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/controller/request/UserModifyRequest.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/User.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/service/UserService.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/user/user/UserModifyAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/user/user/UserSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserModifyIntegrationTest.java
Labels: 🤖 BE, ✨ feature

#81 BE/fix 로그인 페이지 아스키 독스 수정
  be/src/docs/asciidoc/auth/auth.adoc
Labels: 🤖 BE, 📝 docs

#82 SDR-135 Review List View
  fe/src/App.tsx
  fe/src/common/Icon.tsx
  fe/src/common/Modal/Modal.styled.ts
  fe/src/common/Modal/Modal.tsx
  fe/src/common/Portal/Portal.tsx
  fe/src/components/Common/CommonHeader.styled.ts
  fe/src/components/ReviewDetail/Comment/Comment.tsx
  fe/src/components/ReviewDetail/RestaurantProfile/RestaurantProfile.tsx
  fe/src/components/ReviewDetail/TotalRating/TotalRating.tsx
  fe/src/components/ReviewDetail/UserProfile/UserProfile.tsx
  fe/src/components/ReviewList/Feed/Feed.styled.ts
  fe/src/components/ReviewList/Feed/Feed.tsx
  fe/src/components/ReviewList/ReviewList.tsx
  fe/src/components/ReviewWrite/PostScope/PostScope.styled.ts
  fe/src/components/ReviewWrite/RestaurantSearch/RestaurantSearch.styled.ts
  fe/src/components/ReviewWrite/WriteRating/StarRating/StarIcon/StarIcon.tsx
  fe/src/constants/dummyData.ts
  fe/src/constants/size.ts
  fe/src/hooks/useToggle.ts
  fe/src/pages/ReviewDetail/ReviewDetail.tsx
  fe/src/pages/ReviewList/ReviewList.styled.ts
  fe/src/pages/ReviewList/ReviewList.tsx
Labels: 🌐 FE, ✨ feature, 💄 style

#83 SDR-146 User Detail View
  fe/src/App.tsx
  fe/src/components/Common/CommonHeader.tsx
  fe/src/components/UserDetail/FollowButton/FollowButton.styled.ts
  fe/src/components/UserDetail/FollowButton/FollowButton.tsx
  fe/src/components/UserDetail/UserProfilePhoto/UserProfilePhoto.styled.ts
  fe/src/components/UserDetail/UserProfilePhoto/UserProfilePhoto.tsx
  fe/src/pages/UserDetail/userDetail.styled.ts
  fe/src/pages/UserDetail/userDetail.tsx
Labels: 🌐 FE, ✨ feature

#86 SDR-143 리뷰 삭제 API & 테스트
  be/src/docs/asciidoc/review/review.adoc
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/review/controller/ReviewController.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Review.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Tags.java
  be/src/main/java/com/jjikmuk/sikdorak/review/service/ReviewService.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/review/ReviewRemoveAccecptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/review/ReviewSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewRemoveIntegrationTest.java
Labels: 🤖 BE, ✨ feature, 🧪 test

#88 SDR-147 Store Detail View
  fe/src/App.tsx
  fe/src/assets/Location.svg
  fe/src/assets/Phone.svg
  fe/src/common/Icon.tsx
  fe/src/common/Portal/Portal.styled.ts
  fe/src/components/Common/CommonHeader.styled.ts
  fe/src/components/ReviewDetail/Comment/Comment.styled.ts
  fe/src/components/ReviewDetail/WriteComment/WriteComment.styled.ts
  fe/src/components/ReviewList/Feed/Feed.styled.ts
  fe/src/components/ReviewList/Feed/Feed.tsx
  fe/src/components/ReviewWrite/ImgUpload/ImgUpload.styled.ts
  fe/src/components/ReviewWrite/Tag/TagList/TagList.styled.ts
  fe/src/components/UserDetail/FollowButton/FollowButton.styled.ts
  fe/src/constants/dummyData.ts
  fe/src/constants/size.ts
  fe/src/constants/style.ts
  fe/src/constants/text.ts
  fe/src/constants/zIndex.ts
  fe/src/pages/ReviewDetail/ReviewDetail.styled.ts
  fe/src/pages/StoreDetail/StoreDetail.styled.ts
  fe/src/pages/StoreDetail/StoreDetail.tsx
Labels: 🌐 FE, ✨ feature, 💄 style

#92 SDR-163 특정 유저가 작성한 전체 리뷰 조회
  be/.gitignore
  be/src/docs/asciidoc/user/user.adoc
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/aop/UserOnly.java
  be/src/main/java/com/jjikmuk/sikdorak/common/aop/ValidateUserLoginAspect.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/ExceptionCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/review/controller/ReviewController.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Image.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Images.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Review.java
  be/src/main/java/com/jjikmuk/sikdorak/review/domain/Tags.java
  be/src/main/java/com/jjikmuk/sikdorak/review/exception/InvalidReviewImageException.java
  be/src/main/java/com/jjikmuk/sikdorak/review/exception/InvalidReviewImagesException.java
  be/src/main/java/com/jjikmuk/sikdorak/review/repository/ReviewRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/controller/LoginUser.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/controller/UserController.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/controller/response/UserReviewResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/Followers.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/RelationType.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/User.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/service/UserService.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/review/ReviewInsertAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/user/user/UserReviewsSearchByUserIdAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/user/user/UserSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/common/DatabaseConfigurator.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserReviewsSearchByUserIdIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/review/domain/ImageTest.java
  be/src/test/java/com/jjikmuk/sikdorak/review/domain/ImagesTest.java
  be/src/test/java/com/jjikmuk/sikdorak/review/domain/TagsTest.java
  be/src/test/resources/org/springframework/restdocs/templates/asciidoctor/response-fields.snippet
Labels: 🤖 BE, ✨ feature, 🧪 test, ♻️ refactor

#94 SDR-181 CORS Credential 옵션 추가
  be/src/main/java/com/jjikmuk/sikdorak/common/config/WebMvcConfig.java
Labels: 🤖 BE, 🐛 bug

#95 SDR-182 BE 서버 코드/메세지 조회 기능
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/controller/CommonInfoController.java
  be/src/main/java/com/jjikmuk/sikdorak/common/controller/response/CodeAndMessageResponse.java
Labels: 🤖 BE, ✨ feature

#96 SDR-184 refresh 토큰 응답시 sameSite 옵션 추가
  be/src/main/java/com/jjikmuk/sikdorak/user/auth/controller/OAuthController.java
Labels: 🤖 BE, 🐛 bug

#97 SDR-157 유저 조회 API
  be/src/docs/asciidoc/user/user.adoc
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/review/repository/ReviewRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/controller/UserController.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/controller/response/UserProfileRelationStatusResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/controller/response/UserProfileResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/Followers.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/User.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/UserRespository.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/service/UserService.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/user/user/UserFollowUnfollowAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/user/user/UserModifyAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/user/user/UserSearchAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/user/user/UserSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/common/DatabaseConfigurator.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserSearchIntegrationTest.java
Labels: 🤖 BE, ✨ feature

#99 SDR-117 BE - 가게 삭제 API 구현
  be/src/docs/asciidoc/store/store.adoc
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/domain/Deleted.java
  be/src/main/java/com/jjikmuk/sikdorak/store/controller/StoreController.java
  be/src/main/java/com/jjikmuk/sikdorak/store/domain/Store.java
  be/src/main/java/com/jjikmuk/sikdorak/store/service/StoreService.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/store/StoreModifyAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/store/StoreRemoveAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/store/StoreSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/store/StoreRemoveIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/store/StoreSearchIntegrationTest.java
Labels: 🤖 BE, ✨ feature

#100 SDR-175 리뷰 댓글 작성 API 구현
  be/src/docs/asciidoc/comment/comment.adoc
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/jjikmuk/sikdorak/comment/controller/CommentController.java
  be/src/main/java/com/jjikmuk/sikdorak/comment/controller/request/CommentCreateRequest.java
  be/src/main/java/com/jjikmuk/sikdorak/comment/domain/Comment.java
  be/src/main/java/com/jjikmuk/sikdorak/comment/domain/CommentContent.java
  be/src/main/java/com/jjikmuk/sikdorak/comment/exception/InvalidCommentContentException.java
  be/src/main/java/com/jjikmuk/sikdorak/comment/repository/CommentRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/comment/service/CommentService.java
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/ExceptionCodeAndMessages.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/comment/CommentCreateAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/comment/CommentSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/comment/domain/CommentContentTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/comment/CommentCreateIntegrationTest.java
Labels: 🤖 BE, ✨ feature

#102 SDR-78 로그인 처리
  fe/src/App.tsx
  fe/src/common/Loading/Loading.styled.tsx
  fe/src/common/Loading/Loading.tsx
  fe/src/components/Common/CommonHeader.tsx
  fe/src/components/ReviewList/Feed/Feed.tsx
  fe/src/constants/dummyData.ts
  fe/src/constants/statusCode.ts
  fe/src/hooks/useFetch.tsx
  fe/src/index.tsx
  fe/src/pages/Callback/Callback.tsx
  fe/src/pages/Login/Login.styled.ts
  fe/src/pages/Login/Login.tsx
  fe/src/pages/ReviewList/ReviewList.tsx
  fe/src/pages/StoreDetail/StoreDetail.tsx
Labels: 🌐 FE, ✨ feature, 💄 style

#104 SDR-115 유저 탈퇴 API
  be/src/docs/asciidoc/user/user.adoc
  be/src/main/java/com/jjikmuk/sikdorak/comment/service/CommentService.java
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/ExceptionCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/review/service/ReviewService.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/controller/UserController.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/Followers.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/Followings.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/User.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/UserRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/domain/UserRespository.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/service/UserService.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/user/user/UserDeleteAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/user/user/UserFollowUnfollowAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/user/user/UserReviewsSearchByUserIdAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/user/user/UserSearchAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/user/user/UserSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/common/DatabaseConfigurator.java
  be/src/test/java/com/jjikmuk/sikdorak/common/UserDataConfigurator.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/comment/CommentCreateIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewInsertIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewModifyIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewRemoveIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewSearchIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/auth/OAuthArgumentResolverIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/auth/OAuthLoginIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserCreateIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserDeleteIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserFollowUnfollowIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserModifyIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserReviewsSearchByUserIdIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserSearchIntegrationTest.java
Labels: 🤖 BE, ✨ feature, 🧪 test

#106 SDR-201 유저 자신의 프로필 조회 API
  be/src/docs/asciidoc/user/user.adoc
  be/src/main/java/com/jjikmuk/sikdorak/user/user/controller/UserController.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/controller/response/UserDetailProfileResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/controller/response/UserSimpleProfileResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/user/user/service/UserService.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/user/user/UserSearchProfileAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/user/user/UserSearchSelfProfileAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/user/user/UserSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserSearchIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserSearchProfileIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/user/user/UserSearchSelfProfileIntegrationTest.java
Labels: 🤖 BE, ✨ feature

#114 SDR-101 Feed 클릭 시 ReviewDetail Modal 표시
  fe/src/App.tsx
  fe/src/common/Logo/Logo.tsx
  fe/src/components/Common/CommonHeader.styled.ts
  fe/src/components/Common/CommonHeader.tsx
  fe/src/components/ReviewDetail/RestaurantProfile/RestaurantProfile.styled.ts
  fe/src/components/ReviewDetail/UserProfile/UserProfile.styled.ts
  fe/src/components/ReviewList/Feed/Feed.styled.ts
  fe/src/components/ReviewList/Feed/Feed.tsx
  fe/src/components/UserDetail/FollowButton/FollowButton.styled.ts
  fe/src/constants/dummyData.ts
  fe/src/constants/statusCode.ts
  fe/src/constants/zIndex.ts
  fe/src/context/userInfoProvider.tsx
  fe/src/pages/ReviewDetail/ReviewDetail.tsx
  fe/src/pages/UserDetail/userDetail.styled.ts
  fe/src/pages/UserDetail/userDetail.tsx
  fe/src/styles/GlobalStyle.ts
Labels: 🌐 FE, ✨ feature, 💄 style

#115 [SDR-210] common : dev 브랜치 머지 시 팀별 CI만 작동하도록 수정
  .github/workflows/CI-BE.yml
  .github/workflows/CI-FE.yml
Labels: 👫 common, 🏭 Infra

#116 [SDR-211] common : dev 브랜치 PR 시 BE팀 테스트 서버 배포
  .github/workflows/CD-BE.yml
Labels: 🏗️ build, 👫 common, 🏭 Infra

#113 SDR-186 리뷰 댓글 수정 API 구현
  be/src/docs/asciidoc/comment/comment.adoc
  be/src/main/java/com/jjikmuk/sikdorak/comment/controller/CommentController.java
  be/src/main/java/com/jjikmuk/sikdorak/comment/controller/request/CommentModifyRequest.java
  be/src/main/java/com/jjikmuk/sikdorak/comment/domain/Comment.java
  be/src/main/java/com/jjikmuk/sikdorak/comment/exception/NotFoundCommentException.java
  be/src/main/java/com/jjikmuk/sikdorak/comment/service/CommentService.java
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/ExceptionCodeAndMessages.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/comment/CommentCreateAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/comment/CommentModifyAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/comment/CommentSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/common/DataGenerator.java
  be/src/test/java/com/jjikmuk/sikdorak/common/DatabaseConfigurator.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/comment/CommentCreateIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/comment/CommentModifyIntegrationTest.java
Labels: 🤖 BE, ✨ feature

#117 [SDR-100] FE: reviewWrite 페이지 리뷰 반영
  fe/src/components/Common/CommonHeader.tsx
  fe/src/components/ReviewWrite/Calendar/Calendar.tsx
  fe/src/components/ReviewWrite/PostScope/PostScope.tsx
  fe/src/components/ReviewWrite/SelectDay/SelectDay.tsx
  fe/src/context/reviewWriteProvider.tsx
Labels: 🌐 FE, ✨ feature

#119 [SDR-52] common : AWS CDN 자동배포
  .github/workflows/CD-FE.yml
Labels: 🌐 FE, 🏗️ build, 👫 common, 🏭 Infra

#118 [SDR-212] BE : 댓글 삭제 API 구현
  be/src/docs/asciidoc/comment/comment.adoc
  be/src/main/java/com/jjikmuk/sikdorak/comment/controller/CommentController.java
  be/src/main/java/com/jjikmuk/sikdorak/comment/service/CommentService.java
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/comment/CommentRemoveAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/comment/CommentSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/comment/CommentModifyIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/comment/CommentRemoveIntegrationTest.java
Labels: 🤖 BE, ✨ feature

#121 [SDR-208] common : 테라폼을 활용한 BE 팀에서 사용하는 IAM User 생성
  infra/iam/.terraform.lock.hcl
  infra/iam/group.tf
  infra/iam/provider.tf
  infra/iam/user.tf
  infra/iam/variables.tf
Labels: 🏭 Infra

#122 [SDR-52] common : 테라폼을 활용한 FE 팀 정적 리소스 배포용도의 CloudFront
  infra/FE_s3_cloudfront/.terraform.lock.hcl
  infra/FE_s3_cloudfront/cloudfront.tf
  infra/FE_s3_cloudfront/provider.tf
  infra/FE_s3_cloudfront/s3.tf
Labels: 👫 common, 🏭 Infra

#126 [SDR-222] BE : checkstyle LineLength 제약조건 100 -> 120 변경
  be/config-static-analysis/checkstyle/custom-google-checkstyle.xml
Labels: 🤖 BE

#127 [SDR-223] BE : CI 적용되는 paths 수정과 불필요한 로그 제거
  .github/workflows/CI-BE.yml
  be/build.gradle
  be/config-static-analyzer/checkstyle/custom-google-checkstyle.xml
  be/config-static-analyzer/pmd/custom-pmd-rules.xml
Labels: 🤖 BE, 🏗️ build, 👫 common

#125 [SDR-214] BE : 댓글 조회 API 구현
  be/src/docs/asciidoc/comment/comment.adoc
  be/src/main/java/com/jjikmuk/sikdorak/comment/controller/CommentController.java
  be/src/main/java/com/jjikmuk/sikdorak/comment/controller/response/CommentSearchPagingResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/comment/controller/response/CommentSearchResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/comment/repository/CommentRepository.java
  be/src/main/java/com/jjikmuk/sikdorak/comment/service/CommentService.java
  be/src/main/java/com/jjikmuk/sikdorak/common/ResponseCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/config/WebMvcConfig.java
  be/src/main/java/com/jjikmuk/sikdorak/common/controller/CursorPageable.java
  be/src/main/java/com/jjikmuk/sikdorak/common/controller/CursorPageableArgumentResolver.java
  be/src/main/java/com/jjikmuk/sikdorak/common/controller/request/CursorPageRequest.java
  be/src/main/java/com/jjikmuk/sikdorak/common/controller/response/CursorPageResponse.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/ExceptionCodeAndMessages.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/InvalidPageParameterException.java
  be/src/main/java/com/jjikmuk/sikdorak/common/exception/UnsupportedParameterTypeException.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/DocumentFormatGenerator.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/comment/CommentSearchAcceptanceTest.java
  be/src/test/java/com/jjikmuk/sikdorak/acceptance/comment/CommentSnippet.java
  be/src/test/java/com/jjikmuk/sikdorak/common/DataGenerator.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/comment/CommentModifyIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/comment/CommentRemoveIntegrationTest.java
  be/src/test/java/com/jjikmuk/sikdorak/integration/comment/CommentSearchIntegrationTest.java
Labels: 🤖 BE, ✨ feature

#128 [SDR-224] BE : 테스트 서버에 배포 시 승인해야 배포되도록 기능 추가
  .github/workflows/CD-BE.yml
Labels: 🤖 BE, 🏗️ build, 👫 common, 🏭 Infra
